### ISSUE TITLE
Models 

### ISSUE THREAD

**Issue by Idered** [Syncano/syncano-node#38]
```yaml
models:
  post:
    hidden: updated_at, id, $syncano
    computed:
      full_name: `${first_name} ${last_name}`
    scope:
      published:
        - column: published
          value: true
      unpublished:
        - column: published
          value: false
      fromLastWeek:
        - column: published
          value: true
        - column: created_at
          is: gte
          value: new Date(new Date().getTime() - 7 * 24 * 60 * 60 * 1000)
```

**`models.post.hidden`** 
Define columns hidden in results. `$syncano` means "hide all syncano columns"

**`models.post.scope`**
Define named queries
```js
data.post.published().list()
```
