### ISSUE TITLE
Fields method based on schema definition

### ISSUE THREAD

**Issue by Idered** [Syncano/syncano-node#48]
```yaml
endpoints:
  create-wish:
    parameters:
      title:
        type: string
      description:
        type: text
    response:
      success:
        exit_code: 200
        parameters:
          title:
            type: text
```

```js
const wish = {
  title: 'Lorem ipsum',
  description: 'Dolor sit amet',
  uuid: '12ji21d-0ek=2-em12ednfm'
}

response.success(wish)
```

`response.success` undercover should use `fields` method and only return properties defined in the schema. In this case `{title: 'Lorem ipsum'}`  should be returned.

// cc @mkucharz
