### ISSUE TITLE
Invalid response when body is empty

### ISSUE THREAD

**Issue by Dennor** [Syncano/syncano-node#55]
### Expected behaviour

```
HTTP/1.1 200 OK
Server: nginx
Content-Type: text/plain; charset=utf-8
Content-Length: 122
Connection: keep-alive
Keep-Alive: timeout=20
Date: Wed, 06 Dec 2017 13:13:17 GMT
```

When response is returned and is empty, it should stay empty.

### Actual behaviour

```
HTTP/1.1 200 OK
Server: nginx
Content-Type: text/plain; charset=utf-8
Content-Length: 122
Connection: keep-alive
Keep-Alive: timeout=20
Date: Wed, 06 Dec 2017 13:13:17 GMT

{"id":27,"executed_at":"2017-12-06T13:13:17.344436Z","status":"success","duration":810,"result":{"stdout":"","stderr":""}}
```

#### socket.yml
```yaml
name: fail-case
description: Description of fail-case
version: 0.0.1

endpoints:
  fail-case:
    file: fail-case.js
    description: Empty response
    parameters:
    response:
```

#### src/fail-case.js

```javascript
import Server from 'syncano-server';

export default async ctx => {
  const {response} = Server(ctx);
  return response('', 200, 'text/plain', {});
};
```

#### package.json
```json
{
  "license": "MIT",
  "dependencies": {
    "syncano-server": "beta"
  },
  "devDependencies": {
    "eslint": "^4.12.1"
  }
}
```

#### npx s version
```
0.53.0
```
When script returns an empty response, it replaces it with script execution info. Sometimes empty response is an expected behaviour. It can be useful for application/octet-stream and text/plain content-type responses, but it also fails at empty application/json.
