### ISSUE TITLE
Can't upload image files in original quality

### ISSUE THREAD

**Issue by AdamAexol** [Syncano/syncano-node#72]
I can't upload .jpg files in original quality.If I decrease quality files are uploaded correctly, but in original quality, they are corrupted.

**socket.yml**
```
name: storage-master
description: Description of storage-master
version: 0.0.1

classes:
  photo:
    - name: photoFile
      type: file
    - name: user
      type: reference
      target: user_profile
endpoints:
  send_photo:
    file: sendPhoto.js
    parameters:
      photoFile:
        type: file
        description: photo data
        example: "photo data...."
    response:
      mimetype: application/json
```

**sendPhoto.js**
```
import Syncano from 'syncano-server'
import FormData from 'form-data'

export default async ctx => {

  const {data, response, users, logger} = new Syncano(ctx)

  var ff = new FormData()
  ff.append("user", ctx.args.user)
  ff.append("photoFile", ctx.args.photoFile, "photo.jpg")

  const post = await data.photo.create(ff)

  response.json(post)
}
```
